[workspace]
members = [
    "builder",
    "sdk",
]
exclude = [
"acmt",
"admi",
"auth",
"caaa",
"caad",
"caam",
"cafc",
"cafm",
"cafr",
"cain",
"camt",
"canm",
"casp",
"casr",
"catm",
"catp",
"colr",
"dsig",
"fxtr",
"head",
"nvlp",
"pacs",
"pain",
"reda",
"remt",
"secl",
"seev",
"semt",
"sese",
"setr",
"tests",
"tsin",
"tsmt",
"tsrv",
]