name: User Guide

on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      # Cache Build
      - name: Cache Build
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            /usr/bin/plantuml
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      # Install plantuml, mdbook & mdbook-plantuml
      - run: |
        if [[ $(which mdbook) ]]; then
            echo "mdbook is already installed, skipping..."
        else
            echo "Installing mdbook"
            sudo apt-get install -y plantuml 
            cargo install mdbook mdbook-plantuml
        fi
        

      # Build User Guide
      - name: Build User Guide
        run: cd guide && mdbook build

      # Deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./guide/book
